// export const videoData = [
//   {
//     videoId: "video01",
//     title: "ReactJS Tutorial for Beginners",
//     thumbnailUrl:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAmoeq2Dx_jpT6RvvCShHndDkHTRV",
//     videoUrl: "https://www.youtube.com/embed/SqcY0GlETPk?si=hlHQIQEqda0ae7ny",
//     description:
//       "A complete beginner's guide to learning ReactJS, from components to hooks.",
//     channelId: "channel01",
//     channelName: "Tech Insights",
//     uploader: "user01",
//     views: 54000,
//     likes: 3200,
//     dislikes: 112,
//     uploadDate: "2024-11-18",
//     category: "Technology",
//     comments: [
//       {
//         commentId: "comment01",
//         userId: "user02",
//         text: "This tutorial is great! Helps me understand React much better.",
//         timestamp: "2024-11-19T07:50:00Z",
//       },
//       {
//         commentId: "comment02",
//         userId: "user03",
//         text: "Can you also cover React Router in the next video?",
//         timestamp: "2024-11-19T08:00:00Z",
//       },
//     ],
//   },
//   {
//     videoId: "video02",
//     title: "Mastering JavaScript ES6 Features",
//     thumbnailUrl:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0Q2dVQlbmU8CkdDuBUBlKbVSz4HDkTck9WQ&s",
//     videoUrl: "https://www.youtube.com/embed/-3bVuFcteUo?si=5qpLO11ykW05JHtF",
//     description:
//       "Learn the new ES6 features in JavaScript, including arrow functions, promises, and async/await.",
//     channelId: "channel02",
//     channelName: "Code Academy",
//     uploader: "user04",
//     views: 22000,
//     likes: 1500,
//     dislikes: 70,
//     uploadDate: "2024-11-15",
//     category: "Technology",
//     comments: [
//       {
//         commentId: "comment03",
//         userId: "user05",
//         text: "Awesome video! I never understood promises before.",
//         timestamp: "2024-11-16T11:40:00Z",
//       },
//     ],
//   },
//   {
//     videoId: "video03",
//     title: "2024 Hip-Hop Tracks You Need to Hear",
//     thumbnailUrl: "https://i.ytimg.com/vi/2CpwPcREH0s/maxresdefault.jpg",
//     videoUrl: "https://www.youtube.com/embed/sxBhmJJ1PRw?si=eB_-sKwBYZXpVC8I",
//     description: "The hottest hip-hop tracks that are making waves this year.",
//     channelId: "channel03",
//     channelName: "Urban Beats",
//     uploader: "user06",
//     views: 80000,
//     likes: 5400,
//     dislikes: 180,
//     uploadDate: "2024-11-12",
//     category: "Music",
//     comments: [
//       {
//         commentId: "comment04",
//         userId: "user07",
//         text: "The beats on this playlist are fire!",
//         timestamp: "2024-11-13T15:30:00Z",
//       },
//     ],
//   },
//   {
//     videoId: "video04",
//     title: "Building a Gaming PC for 2024",
//     thumbnailUrl:
//       "https://store.hp.com/app/assets/images/uploads/prod/how-to-build-a-gaming-computer-hero1555706958293.jpg",
//     videoUrl: "https://www.youtube.com/embed/yw02dHyP0K0?si=p_dIdAq6xzwXJyST",
//     description:
//       "Step-by-step guide to building a gaming PC with the latest components.",
//     channelId: "channel04",
//     channelName: "Tech Masters",
//     uploader: "user08",
//     views: 35000,
//     likes: 2500,
//     dislikes: 95,
//     uploadDate: "2024-11-10",
//     category: "Gaming",
//     comments: [
//       {
//         commentId: "comment05",
//         userId: "user09",
//         text: "Very informative! Exactly what I needed to upgrade my system.",
//         timestamp: "2024-11-11T14:25:00Z",
//       },
//     ],
//   },
//   {
//     videoId: "video05",
//     title: "The Funniest Dog Videos Ever",
//     thumbnailUrl:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6_F7fZfIzyO6HwaBdSANt0WKW1sY5Y_VXbQ&s",
//     videoUrl: "https://www.youtube.com/embed/IZzeLnaygME?si=D7sIWo1OEkAKb0Db",
//     description: "A compilation of the most hilarious and adorable dog videos.",
//     channelId: "channel05",
//     channelName: "Paws & Pals",
//     uploader: "user10",
//     views: 95000,
//     likes: 8200,
//     dislikes: 210,
//     uploadDate: "2024-11-05",
//     category: "Entertainment",
//     comments: [
//       {
//         commentId: "comment06",
//         userId: "user11",
//         text: "I laughed so hard at the last one, especially the one with the golden retriever!",
//         timestamp: "2024-11-06T09:50:00Z",
//       },
//     ],
//   },
//   {
//     videoId: "video06",
//     title: "Top 5 FPS Games of 2024",
//     thumbnailUrl:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFtQxAbt-VTucRKELW7hVUCiU1M8zDPGZN9Q&s",
//     videoUrl: "https://www.youtube.com/embed/SfbxulkcSjU?si=HbIwAtzFeLqEGa7L",
//     description:
//       "Discover the best first-person shooter games you should play this year.",
//     channelId: "channel06",
//     channelName: "Gamer’s Paradise",
//     uploader: "user12",
//     views: 43000,
//     likes: 3100,
//     dislikes: 115,
//     uploadDate: "2024-11-09",
//     category: "Gaming",
//     comments: [
//       {
//         commentId: "comment07",
//         userId: "user13",
//         text: "I can't wait to check out the new Call of Duty!",
//         timestamp: "2024-11-10T12:10:00Z",
//       },
//     ],
//   },
//   {
//     videoId: "video07",
//     title: "How to Edit Videos for YouTube",
//     thumbnailUrl:
//       "https://cc-prod.scene7.com/is/image/CCProdAuthor/Introduction_to_video_editing_900x420?$pjpeg$&jpegSize=200&wid=900",
//     videoUrl: "https://www.youtube.com/embed/64nXeN96FxU?si=6yVuPxGYnlVWfgR_",
//     description:
//       "A beginner's guide to video editing using free software for YouTube creators.",
//     channelId: "channel07",
//     channelName: "Creator's Studio",
//     uploader: "user14",
//     views: 27000,
//     likes: 1800,
//     dislikes: 50,
//     uploadDate: "2024-11-14",
//     category: "Technology",
//     comments: [
//       {
//         commentId: "comment08",
//         userId: "user15",
//         text: "Great tips, I’m going to try these for my next video!",
//         timestamp: "2024-11-15T14:30:00Z",
//       },
//     ],
//   },
//   {
//     videoId: "video08",
//     title: "Best Productivity Apps for Students",
//     thumbnailUrl:
//       "https://cdn.prod.website-files.com/60c0cec90f57824353f55893/628788700eb1a86323a804cf_Producitvity%20apps%20for%20students.png",
//     videoUrl: "https://www.youtube.com/embed/vqSHNCZKApc?si=5zkYQtMbewS_H4C3",
//     description:
//       "A list of the top apps for students to stay organized and focused.",
//     channelId: "channel08",
//     channelName: "Student Tech",
//     uploader: "user16",
//     views: 32000,
//     likes: 2300,
//     dislikes: 80,
//     uploadDate: "2024-11-06",
//     category: "Technology",
//     comments: [
//       {
//         commentId: "comment09",
//         userId: "user17",
//         text: "The note-taking apps you mentioned are life-changing!",
//         timestamp: "2024-11-07T13:00:00Z",
//       },
//     ],
//   },
//   {
//     videoId: "video09",
//     title: "Epic Action Movie Scenes",
//     thumbnailUrl:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzEzRZWbulMTCheelES8nWsqn7KwOZnxiQgQ&s",
//     videoUrl: "https://www.youtube.com/embed/8luaY8tEElc?si=Foy59N1FUymhNIrC",
//     description:
//       "A collection of the most intense action scenes from Hollywood blockbusters.",
//     channelId: "channel09",
//     channelName: "Cinephile Central",
//     uploader: "user18",
//     views: 60000,
//     likes: 4500,
//     dislikes: 130,
//     uploadDate: "2024-11-02",
//     category: "Entertainment",
//     comments: [
//       {
//         commentId: "comment10",
//         userId: "user19",
//         text: "The car chase from Fast & Furious was insane!",
//         timestamp: "2024-11-03T10:30:00Z",
//       },
//     ],
//   },
//   {
//     videoId: "video10",
//     title: "Best House Music of 2024",
//     thumbnailUrl:
//       "https://is1-ssl.mzstatic.com/image/thumb/yTSbkGaaGLABNT3bhsqT4Q/1200x600wp-60.jpg",
//     videoUrl: "https://www.youtube.com/embed/ZX6ue4yGSvs?si=rqwvQEzjcjhHUHao",
//     description: "The best house music tracks to keep you moving all night.",
//     channelId: "channel10",
//     channelName: "House Vibes",
//     uploader: "user20",
//     views: 86000,
//     likes: 7100,
//     dislikes: 250,
//     uploadDate: "2024-10-29",
//     category: "Music",
//     comments: [
//       {
//         commentId: "comment11",
//         userId: "user21",
//         text: "These tracks are perfect for a party!",
//         timestamp: "2024-10-30T17:50:00Z",
//       },
//     ],
//   },
// ];
